# using `kubectl create -f volumes.yaml -n d44242`.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sas-risk-cirrus-core-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: sas
